version: '3.7'
services:
  netbox: &netbox
    links:
      - netbox-postgres:netbox-postgres
      - netbox-redis:netbox-redis
      - redis-cache:redis-cache
    build: ./netbox/
    image: netbox:v4.0.0-1
    env_file: ./env/netbox.env
    user: 'netbox:root'
    healthcheck:
      start_period: 60s
      timeout: 3s
      interval: 15s
      retries: 5
      test: ["CMD-SHELL", "curl -f http://localhost:8080/login/ || exit 1"]

    volumes:
    - netbox-media-files:/opt/netbox/netbox/media:rw
    - netbox-reports-files:/opt/netbox/netbox/reports:rw
    - netbox-scripts-files:/opt/netbox/netbox/scripts:rw

  netbox-worker:
    <<: *netbox
    links:
      - netbox:netbox
    command:
      - python
      - /opt/netbox/netbox/manage.py
      - rqworker
    healthcheck:
      start_period: 20s
      timeout: 3s
      interval: 15s
      retries: 5
      test: "ps -aux | grep -v grep | grep -q rqworker || exit 1"

  netbox-housekeeping:
    <<: *netbox
    links:
      - netbox:netbox
    command:
      - /opt/netbox/contrib/netbox-housekeeping.sh
    healthcheck:
      start_period: 20s
      timeout: 3s
      interval: 15s
      retries: 5
      test: "ps -aux | grep -v grep | grep -q housekeeping|| exit 1"

  # postgres
  netbox-postgres:
    image: postgres:16.3-alpine
    container_name: netbox-postgres
    env_file: ./env/postgres.env
    healthcheck:
      start_period: 20s
      timeout: 3s
      interval: 10s
      retries: 5
      test: ["CMD-SHELL", "pg_isready -q -h localhost -p 5432 -U netbox"]

    ports:
      - "5433:5432"
    volumes:
      - netbox_postgres_data:/var/lib/postgresql/data

  # redis
  netbox-redis:
    image: docker.io/redis:7-alpine
    container_name: netbox-redis
    command:
    - sh
    - -c # this is to evaluate the $REDIS_PASSWORD from the env
    - redis-server --appendonly yes --requirepass $$REDIS_PASSWORD ## $$ because of docker-compose
    env_file: ./env/redis.env
    healthcheck:
      start_period: 20s
      timeout: 3s
      interval: 10s
      retries: 5
      test: ["CMD", "redis-cli", "ping"]
    volumes:
    - netbox-redis-data:/data

  redis-cache:
    image: docker.io/redis:7-alpine
    container_name: redis-cache
    command:
    - sh
    - -c # this is to evaluate the $REDIS_PASSWORD from the env
    - redis-server --requirepass $$REDIS_PASSWORD ## $$ because of docker-compose
    env_file: ./env/redis-cache.env
    healthcheck:
      start_period: 20s
      timeout: 3s
      interval: 10s
      retries: 5
      test: ["CMD", "redis-cli", "ping"]
    volumes:
    - netbox-redis-cache-data:/data


volumes:
  netbox_postgres_data:
  netbox-media-files:
    driver: local
  netbox-redis-cache-data:
    driver: local
  netbox-redis-data:
    driver: local
  netbox-reports-files:
    driver: local
  netbox-scripts-files:
    driver: local











